### ISSUE TITLE
Compressing world file issue 

### ISSUE THREAD

**Issue by MoeHunt3r** [rypengu23/AutoWorldTools#5]
Hey there! 
Just installed the plugin on my 1.18 Server and theres one issue when trying to backup the worlds while the server is running. 
"The process cannot access the file because another process has locked part of the file"

`[18:02:39] [Craft Scheduler Thread - 3 - AutoWorldTools/INFO]: [AutoWorldTools] Compressing world file...  World:world
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: java.nio.file.FileSystemException: .\world\session.lock -> C:\worldBackup\world\work20211220180239\world\session.lock: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:209)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.nio.file.Files.copy(Files.java:1305)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:850)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1312)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:699)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:630)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:531)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:502)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.util.BackupUtil.createWorldFileZip(BackupUtil.java:193)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.command.Command_Backup$1.run(Command_Backup.java:60)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:03:19] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: C:\worldBackup\world\work20211220180239\world\region\r.-2.-4.mca (Das System kann die angegebene Datei nicht finden)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:49)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:36)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:365)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.ZipFile.addFolder(ZipFile.java:340)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.util.BackupUtil.createWorldFileZip(BackupUtil.java:205)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.command.Command_Backup$1.run(Command_Backup.java:60)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: Caused by: java.io.FileNotFoundException: C:\worldBackup\world\work20211220180239\world\region\r.-2.-4.mca (Das System kann die angegebene Datei nicht finden)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:73)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:29)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AddFolderToZipTask.executeTask(AddFolderToZipTask.java:17)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:42)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	... 11 more
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: [AutoWorldTools] Backup failure. Not Found world. World:world
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: org.apache.commons.io.IOExceptionList: C:\worldBackup\world\work20211220180239
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.util.BackupUtil.createWorldFileZip(BackupUtil.java:214)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at AutoWorldTools-1.6.jar//com.github.rypengu23.autoworldtools.command.Command_Backup$1.run(Command_Backup.java:60)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: Caused by: java.io.IOException: Cannot delete file: C:\worldBackup\world\work20211220180239\world
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:324)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	... 9 more
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: Caused by: org.apache.commons.io.IOExceptionList: C:\worldBackup\world\work20211220180239\world\region\r.-31.-1.mca
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.PathUtils.setReadOnly(PathUtils.java:939)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:159)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	... 10 more
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: Caused by: java.nio.file.NoSuchFileException: C:\worldBackup\world\work20211220180239\world\region\r.-31.-1.mca
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsLinkSupport.getFinalPath(WindowsLinkSupport.java:108)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Dos.updateAttributes(WindowsFileAttributeViews.java:228)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Dos.setReadOnly(WindowsFileAttributeViews.java:248)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	at org.apache.commons.io.file.PathUtils.setReadOnly(PathUtils.java:914)
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/WARN]: 	... 18 more
[18:05:33] [Craft Scheduler Thread - 3 - AutoWorldTools/INFO]: [AutoWorldTools] Compression complete. World:world`

**Comment by rypengu23** [comment]
Thank you for reporting! Now that I've been able to reproduce this issue, I'll work on fixing it.

**Comment by rypengu23** [comment]
Sorry for the delay, but the fix is complete.
